version: "2.1"

services:
  docker-intro:
    image: docker-intro
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 src/index.ts
